<?php
/**
 * @file
 * Code for Custom Blocks.
 */

/**
 * Implements hook_block_configure().
 */
function auge_custom_blocks_block_configure($delta = '') {
  $form = array();
  switch ($delta) {
    case 'contact_information':
      $default = array(
        'value' => '<p>' . t('​Campus Rodrigo Facio, UCR.') . '</p>' . '<p>' . t('"Casa emprendedora María Teresa Obregón", 100 meters east and 100 north from the "Fuente de la Hispanidad", San Pedro, San José.') . '</p>' .   '<p>' . t('Phone:') . '</p>' . '<p>' . t('+506 2511-1334') . '</p>' . '<p>' . t('Contact:') . '</p>' . '<p>' . t('luisalonso@augeucr.com') . '</p>',
        'format' => 'manati_texto_formato',
      );
      $text_body_field_contact = variable_get('auge_ftr_blocks_text_body_contact_english', $default);
      $form['auge_ftr_blocks_text_body_contact_english'] = array(
        '#type' => 'text_format',
        '#title' => t('Here goes the contact information.'),
        '#default_value' => $text_body_field_contact['value'],
        '#format' => $text_body_field_contact['format'],
      );
      break;
    case 'contact_information_spanish':
      $default = array(
        'value' => '<p>' . t('​Campus Rodrigo Facio, UCR.') . '</p>' . '<p>' . t('Casa emprendedora María Teresa Obregón, 100 metros este y 100 norte de la Fuente de la Hispanidad, San Pedro, San José.') . '</p>' .   '<p>' . t('Teléfono:') . '</p>' . '<p>' . t('+506 2511-1334') . '</p>' . '<p>' . t('Contacto:') . '</p>' . '<p>' . t('luisalonso@augeucr.com') . '</p>',
        'format' => 'manati_texto_formato',
      );
      $text_body_field_contact = variable_get('auge_ftr_blocks_text_body_contact_spanish', $default);
      $form['auge_ftr_blocks_text_body_contact_spanish'] = array(
        '#type' => 'text_format',
        '#title' => t('Ingrese aquí la información de contacto.'),
        '#default_value' => $text_body_field_contact['value'],
        '#format' => $text_body_field_contact['format'],
      );
      break;
  }
  return $form;
}
/**
 * Implements hook_block_info().
 */
function auge_custom_blocks_block_info() {
  return array(
    'contact_information' => array(
      'info' => t('Contact information: English.'),
      'cache' => DRUPAL_CACHE_GLOBAL,
    ),
    'contact_information_spanish' => array(
      'info' => t('Contact information: Spanish.'),
      'cache' => DRUPAL_CACHE_GLOBAL,
    ),
    'footer_logos' => array(
      'info' => t('Footer logos'),
      'cache' => DRUPAL_CACHE_GLOBAL,
    ),
  );
}

/**
 * Implements hook_block_view().
 */
function auge_custom_blocks_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'contact_information':
      $default = array(
        'value' => '<p>' . t('​Campus Rodrigo Facio, UCR.') . '</p>' . '<p>' . t('"Casa emprendedora María Teresa Obregón", 100 meters east and 100 north from the "Fuente de la Hispanidad", San Pedro, San José.') . '</p>' .   '<p>' . t('Phone:') . '</p>' . '<p>' . t('+506 2511-1334') . '</p>' . '<p>' . t('Contact:') . '</p>' . '<p>' . t('luisalonso@augeucr.com') . '</p>',
        'format' => 'manati_texto_formato',
      );
      $custom_block_text = variable_get('auge_ftr_blocks_text_body_contact_english', $default);
      $block['subject'] = t('');
      $block['content'] = array(
        'message' => array(
          '#type' => 'markup',
          '#markup' => check_markup($custom_block_text['value'], $custom_block_text['format'] ),
        ),
      );
      break;
    case 'contact_information_spanish':
      $default = array(
        'value' => '<p>' . t('​Campus Rodrigo Facio, UCR.') . '</p>' . '<p>' . t('Casa emprendedora María Teresa Obregón, 100 metros este y 100 norte de la Fuente de la Hispanidad, San Pedro, San José.') . '</p>' .   '<p>' . t('Teléfono:') . '</p>' . '<p>' . t('+506 2511-1334') . '</p>' . '<p>' . t('Contacto:') . '</p>' . '<p>' . t('luisalonso@augeucr.com') . '</p>',
        'format' => 'manati_texto_formato',
      );
      $custom_block_text = variable_get('auge_ftr_blocks_text_body_contact_spanish', $default);
      $block['subject'] = t('');
      $block['content'] = array(
        'message' => array(
          '#type' => 'markup',
          '#markup' => check_markup($custom_block_text['value'], $custom_block_text['format'] ),
        ),
      );
      break;
      case 'footer_logos':
        $footer_logos_html = '<div class="footer-logos">
            <div class="footer-logos--partof">
              <p>Formamos parte de:</p>
              <div class="footer-logos--partof-images">
                <img src="/sites/all/themes/auge-theme/images/AUGE-UCR.png" alt="UCR logo">
                <img src="/sites/all/themes/auge-theme/images/AUGE-FUCR.png" alt="FUCR logo">
                <img src="/sites/all/themes/auge-theme/images/AUGE-SMBUBI.png" alt="SMBUBI logo">
              </div>
            </div>
            <div class="footer-logos--madeby">
              <p>Desarrollo web por:</p>
              <div class="footer-logos--madeby-images">
                <img src="/sites/all/themes/auge-theme/images/AUGE-SMBUBI.png" alt="Manati logo">
              </div>
            </div>
          </div>';
        $block['subject'] = t('');
        $block['content'] = array(
          'message' => array(
            '#type' => 'markup',
            '#markup' => $footer_logos_html,
          ),
        );
        break;
  }
  return $block;
}
/**
 * Implements hook_block_save().
 */
function auge_custom_blocks_block_save($delta = '', $edit = array()) {
  switch ($delta) {
    case 'contact_information':
      variable_set('text_body_field_contact_contact_english', $edit['text_body_field_contact_contact_english']);
      break;
    case 'contact_information_spanish':
      variable_set('text_body_field_contact_contact_spanish', $edit['text_body_field_contact_contact_spanish']);
      break;
    case 'footer_logos':
      variable_set('text_body_field_footer_logos');
      break;
  }
}
