<?php
/**
* @file
* Code for the Auge: Pages - Contact feature.
*/
include_once 'auge_pages_contact.features.inc';
/*
* Implements hook_form_alter()
*/
function auge_pages_contact_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'contact_form_entityform_edit_form') {
    $form['field_contacted_email']['#access'] = FALSE;
  }
}
/**
*Implements hook_entity_presave()
*/
function auge_pages_contact_entity_presave($entity, $type) {
    if ($type == 'entityform') {
      $tid = $entity->field_subject[LANGUAGE_NONE][0]['tid'];
      $term = taxonomy_term_load($tid);
      $term_translated = i18n_taxonomy_term_get_translation($term, 'en');
      $name = $term_translated->name;
      switch ($name) {
        case 'Entrepreneur':
        $entity->field_contacted_email[LANGUAGE_NONE][0]['email'] = 'carolina@augeucr.com';
        break;
        case 'Learn':
        $entity->field_contacted_email[LANGUAGE_NONE][0]['email'] = 'anajavier@augeucr.com';
        break;
        case 'Invest':
        $entity->field_contacted_email[LANGUAGE_NONE][0]['email'] = 'david.ramirez@augeucr.com';
        break;
        case 'Mentor':
        $entity->field_contacted_email[LANGUAGE_NONE][0]['email'] = 'carolina@augeucr.com';
        break;
        case 'General information':
        $entity->field_contacted_email[LANGUAGE_NONE][0]['email'] = 'info@augeucr.com';
        break;
        case 'Services':
        $entity->field_contacted_email[LANGUAGE_NONE][0]['email'] = 'allison@augeucr.com';
        break;
        case 'Incubarse':
        $entity->field_contacted_email[LANGUAGE_NONE][0]['email'] = 'carolina@augeucr.com';
        break;
        case 'Aprender':
        $entity->field_contacted_email[LANGUAGE_NONE][0]['email'] = 'anajavier@augeucr.com';
        break;
        case 'Impulsar':
        $entity->field_contacted_email[LANGUAGE_NONE][0]['email'] = 'david.ramirez@augeucr.com';
        break;
        case 'Acompañar':
        $entity->field_contacted_email[LANGUAGE_NONE][0]['email'] = 'carolina@augeucr.com';
        break;
        case 'Información general':
        $entity->field_contacted_email[LANGUAGE_NONE][0]['email'] = 'info@augeucr.com';
        break;
        case 'Servicios':
        $entity->field_contacted_email[LANGUAGE_NONE][0]['email'] = 'allison@augeucr.com';
        break;
      }
    }
  }
