<?php
/**
 * @file
 * Code for the Auge Footer-Sidebar blocks feature.
 */

include_once 'auge_ftr_blocks.features.inc';
/**
 * Implements hook_block_configure().
 */
function auge_ftr_blocks_block_configure($delta = '') {
  $form = array();
  switch ($delta) {
    case 'contact_information':
      $default = array(
        'value' => '<p>' . t('​Campus Rodrigo Facio, UCR.') . '</p>' . '<p>' . t('"Casa emprendedora María Teresa Obregón", 100 meters east and 100 north from the "Fuente de la Hispanidad", San Pedro, San José.') . '</p>' .   '<p>' . t('Phone:') . '</p>' . '<p>' . t('+506 2511-1334') . '</p>' . '<p>' . t('Contact:') . '</p>' . '<p>' . t('luisalonso@augeucr.com') . '</p>',
        'format' => 'manati_texto_formato',
      );
      $text_body_field_contact = variable_get('auge_ftr_blocks_text_body_contact_english', $default);
      $form['auge_ftr_blocks_text_body_contact_english'] = array(
        '#type' => 'text_format',
        '#title' => t('Here goes the contact information.'),
        '#default_value' => $text_body_field_contact['value'],
        '#format' => $text_body_field_contact['format'],
      );
      break;
    case 'contact_information_spanish':
      $default = array(
        'value' => '<p>' . t('​Campus Rodrigo Facio, UCR.') . '</p>' . '<p>' . t('"Casa emprendedora María Teresa Obregón", 100 meters east and 100 north from the "Fuente de la Hispanidad", San Pedro, San José.') . '</p>' .   '<p>' . t('Phone:') . '</p>' . '<p>' . t('+506 2511-1334') . '</p>' . '<p>' . t('Contact:') . '</p>' . '<p>' . t('luisalonso@augeucr.com') . '</p>',
        'format' => 'manati_texto_formato',
      );
      $text_body_field_contact = variable_get('auge_ftr_blocks_text_body_contact_spanish', $default);
      $form['auge_ftr_blocks_text_body_contact_spanish'] = array(
        '#type' => 'text_format',
        '#title' => t('Ingrese aquí la información de contacto.'),
        '#default_value' => $text_body_field_contact['value'],
        '#format' => $text_body_field_contact['format'],
      );
      break;
  }
  return $form;
}
/**
 * Implements hook_block_info().
 */
function auge_ftr_blocks_block_info() {
  return array(
    'contact_information' => array(
      'info' => t('Contact information'),
      'cache' => DRUPAL_CACHE_GLOBAL,
    ),
    'contact_information_spanish' => array(
      'info' => t('Contact information in spanish'),
      'cache' => DRUPAL_CACHE_GLOBAL,
    ),
  );
}

/**
 * Implements hook_block_view().
 */
function auge_ftr_blocks_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'contact_information':
      $default = array(
        'value' => '<p>' . t('​Campus Rodrigo Facio, UCR.') . '</p>' . '<p>' . t('"Casa emprendedora María Teresa Obregón", 100 meters east and 100 north from the "Fuente de la Hispanidad", San Pedro, San José.') . '</p>' .   '<p>' . t('Phone:') . '</p>' . '<p>' . t('+506 2511-1334') . '</p>' . '<p>' . t('Contact:') . '</p>' . '<p>' . t('luisalonso@augeucr.com') . '</p>',
        'format' => 'manati_texto_formato',
      );
      $custom_block_text = variable_get('auge_ftr_blocks_text_body_contact_english', $default);
      $block['subject'] = t('Contact');
      $block['content'] = array(
        'message' => array(
          '#type' => 'markup',
          '#markup' => check_markup($custom_block_text['value'], $custom_block_text['format'] ),
        ),
      );
      break;
    case 'contact_information_spanish':
      $default = array(
        'value' => '<p>' . t('​Campus Rodrigo Facio, UCR.') . '</p>' . '<p>' . t('"Casa emprendedora María Teresa Obregón", 100 meters east and 100 north from the "Fuente de la Hispanidad", San Pedro, San José.') . '</p>' .   '<p>' . t('Phone:') . '</p>' . '<p>' . t('+506 2511-1334') . '</p>' . '<p>' . t('Contact:') . '</p>' . '<p>' . t('luisalonso@augeucr.com') . '</p>',
        'format' => 'manati_texto_formato',
      );
      $custom_block_text = variable_get('auge_ftr_blocks_text_body_contact_spanish', $default);
      $block['subject'] = t('Contacto');
      $block['content'] = array(
        'message' => array(
          '#type' => 'markup',
          check_markup($custom_block_text['value'], $custom_block_text['format'] ),
        ),
      );
      break;
  }
  return $block;
}
/**
 * Implements hook_block_save().
 */
function auge_ftr_blocks_block_save($delta = '', $edit = array()) {
  switch ($delta) {
    case 'contact_information':
      variable_set('text_body_field_contact_contact_english', $edit['text_body_field_contact_contact_english']);
      break;
  case 'contact_information_spanish':
    variable_set('text_body_field_contact_contact_spanish', $edit['text_body_field_contact_contact_spanish']);
    break;
  }
}
/**
 * Get for information of the contact block.
 */
function auge_ftr_blocks_contact_get_information_block() {
  return '<p>' . t('​Campus Rodrigo Facio, UCR.') . '</p>' . '<p>' . t('"Casa emprendedora María Teresa Obregón", 100 meters east and 100 north from the "Fuente de la Hispanidad", San Pedro, San José.') . '</p>' .   '<p>' . t('Phone:') . '</p>' . '<p>' . t('+506 2511-1334') . '</p>' . '<p>' . t('Contact:') . '</p>' . '<p>' . t('luisalonso@augeucr.com') . '</p>';
}


/**
 * Get for information of the who we are block.
 */
function auge_ftr_blocks_who_get_information_block() {
  return '<p>' . t('Lorem') . '</p>';
}
