<?php
/**
 * @file
 * Code for the Auge Footer-Sidebar blocks feature.
 */

include_once 'auge_ftr_blocks.features.inc';

/**
 * Implements hook_block_info().
 */
function auge_ftr_blocks_block_info() {
  return array(
    'contact_information' => array(
      'info' => t('Contact information'),
      'cache' => DRUPAL_CACHE_GLOBAL,
    ),
    'who_we_are_information' => array(
      'info' => t('Who we are information'),
      'cache' => DRUPAL_CACHE_GLOBAL,
    ),
  );
}

/**
 * Implements hook_block_view().
 */
function auge_ftr_blocks_block_view($delta) {
  $block = array();
  switch ($delta) {
    case 'contact_information':
      $block['subject'] = t('Contact form');
      $block['content'] = auge_ftr_blocks_contact_get_information_block();
      break;
    case 'who_we_are_information':
      $block['subject'] = t('Who we are');
      $block['content'] = auge_ftr_blocks_who_get_information_block();
      break;
  }
  return $block;
}
/**
 * Get for information of the contact block.
 */
function auge_ftr_blocks_contact_get_information_block() {
  return '<p>' . t('​Campus Rodrigo Facio, UCR.') .
  '</p>' . '<p>' . t('"Casa emprendedora María Teresa Obregón",
  100 meters east and 100 north from the "Fuente de la Hispanidad",
  San Pedro, San José.') . '</p>' .   '<p>' . t('Phone:') . '</p>' . '<p>' .
  t('+506 2511-1334') . '</p>' . '<p>' .
  t('Contact:') . '</p>' . '<p>' . t('luisalonso@augeucr.com') . '</p>';
}


/**
 * Get for information of the who we are block.
 */
function auge_ftr_blocks_who_get_information_block() {
  return '<p>' . t('Lorem') . '</p>';
}
