<?php
/**
 * @file
 * auge_crumbs.strongarm.inc
 */

/**
 * Implements hook_strongarm().
 */
function auge_crumbs_strongarm() {
  $export = array();

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'crumbs_home_link_title';
  $strongarm->value = 'Home';
  $export['crumbs_home_link_title'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'crumbs_minimum_trail_items';
  $strongarm->value = '3';
  $export['crumbs_minimum_trail_items'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'crumbs_node_parent_patterns';
  $strongarm->value = array(
    'activity' => 'Actividades / [node:title]',
    'blog_post' => 'Blog / [node:title]',
    'front_page_images' => '',
    'personnel' => '',
    'projects' => '',
    'stages' => '',
  );
  $export['crumbs_node_parent_patterns'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'crumbs_original_theme_breadcrumb';
  $strongarm->value = array(
    'auge' => 'theme_breadcrumb',
    'seven' => 'theme_breadcrumb',
  );
  $export['crumbs_original_theme_breadcrumb'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'crumbs_override_theme_breadcrumb';
  $strongarm->value = array(
    'theme_breadcrumb' => 'theme_breadcrumb',
  );
  $export['crumbs_override_theme_breadcrumb'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'crumbs_separator';
  $strongarm->value = ' &raquo; ';
  $export['crumbs_separator'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'crumbs_separator_span';
  $strongarm->value = 0;
  $export['crumbs_separator_span'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'crumbs_show_current_page';
  $strongarm->value = '5';
  $export['crumbs_show_current_page'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'crumbs_show_front_page';
  $strongarm->value = 0;
  $export['crumbs_show_front_page'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'crumbs_weights';
  $strongarm->value = array(
    'crumbs.entityParent.node.blog_post' => 1,
    'crumbs.entityParent.node.activity' => 2,
    'menu.link_title.main-menu' => 3,
    'taxonomy.termReference.*' => 4,
    '*' => FALSE,
    'crumbs.home_title' => FALSE,
  );
  $export['crumbs_weights'] = $strongarm;

  return $export;
}
